name: sante_en_poche
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.0
  intl: ^0.19.0
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  shared_preferences: ^2.2.3
  cloud_firestore: ^4.17.3
  local_auth: ^2.2.0
  firebase_database: ^10.5.5
  image_picker: ^1.1.2
  firebase_storage: ^11.7.7
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:

 
  uses-material-design: true
  assets:
   - assets/images/background/
   - assets/images/login/
   - assets/images/signup/
   - assets/images/confirmer/
   - assets/images/home/
   - assets/images/myfile/
   - assets/images/search/