// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-bYwOcTBRZK0Tk9SP0f-G9wkO3JxLYPU',
    appId: '1:898467525980:web:dfca22bdefe5043e60bd99',
    messagingSenderId: '898467525980',
    projectId: 'sante-b1cde',
    authDomain: 'sante-b1cde.firebaseapp.com',
    storageBucket: 'sante-b1cde.appspot.com',
    measurementId: 'G-ZPZZ5ZLY6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvfRjHjHvnPW-RElWkuwFnVbKd48MAMKk',
    appId: '1:898467525980:android:450634d2f9416b7f60bd99',
    messagingSenderId: '898467525980',
    projectId: 'sante-b1cde',
    storageBucket: 'sante-b1cde.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKqN5CiG7Az0uSiJnTtCk0CGhTwOwTMqA',
    appId: '1:898467525980:ios:1a0aacb5ff3ac7f460bd99',
    messagingSenderId: '898467525980',
    projectId: 'sante-b1cde',
    storageBucket: 'sante-b1cde.appspot.com',
    iosBundleId: 'com.example.santeEnPoche',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKqN5CiG7Az0uSiJnTtCk0CGhTwOwTMqA',
    appId: '1:898467525980:ios:1a0aacb5ff3ac7f460bd99',
    messagingSenderId: '898467525980',
    projectId: 'sante-b1cde',
    storageBucket: 'sante-b1cde.appspot.com',
    iosBundleId: 'com.example.santeEnPoche',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-bYwOcTBRZK0Tk9SP0f-G9wkO3JxLYPU',
    appId: '1:898467525980:web:7c3b137d98d9b56c60bd99',
    messagingSenderId: '898467525980',
    projectId: 'sante-b1cde',
    authDomain: 'sante-b1cde.firebaseapp.com',
    storageBucket: 'sante-b1cde.appspot.com',
    measurementId: 'G-1J9D72LTC3',
  );
}
